language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
os:
  - linux
  - osx
notifications:
  email: false
before_script: 
  - npm i -g nato-cli
script:
  - nato abcdefghi jklmnOPQRSTu vwx yz
