language: node_js

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  
os:
  - linux
  - osx
  
cache:
  yarn: true
  directories:
    - node_modules
    
install:
  - yarn

before_script: 
  - yarn global add nato-cli

script:
  - nato abcdefghijklmnOPQRSTu vwx yz
