language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
os:
  - linux
  - osx
notifications:
  email: false
install:
  - yarn
before_script: 
  - yarn global add nato-cli
script:
  - nato abcdefghi jklmnOPQRSTu vwx yz
