language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
os:
  - linux
  - osx
  - windows
dist:
  - trusty
  - bionic
  - xenial
notifications:
  email: false
before_script: 
  - npm i -g nato-cli
script:
  - nato abcdefghi jklmnOPQRSTu vwx yz
